export const fakeTasks = [
  {
    TaskID: 1,
    Assignee: "John Doe",
    Title: "Task 1",
    Description: "Description for Task 1",
    Status: "todo",
    Tags: "meeting,urgent",
    StartDate: "2023-10-01",
    EndDate: "",
    Priority: "high",
    CreatedBy: 1,
    AssignedTo: 2,
    Subtasks: [
      { SubtaskID: 1, Title: "Subtask 1", IsCompleted: false },
      { SubtaskID: 2, Title: "Subtask 2", IsCompleted: true },
    ],
  },
  {
    TaskID: 2,
    Title: "Task 2",
    Assignee: "John Doe",
    Description: "Description for Task 2",
    Status: "in_progress",
    Tags: "meeting,urgent",
    StartDate: "2023-10-01",
    EndDate: "2023-10-15",
    Priority: "medium",
    CreatedBy: 1,
    AssignedTo: 2,
    Subtasks: [
      { SubtaskID: 3, Title: "Subtask 3", IsCompleted: false },
      { SubtaskID: 4, Title: "Subtask 4", IsCompleted: true },
    ],
  },
  {
    TaskID: 3,
    Title: "Task 3",
    Assignee: "Tarin",
    Description: "Description for Task 3",
    Status: "done",
    Tags: "meeting,urgent",
    StartDate: "2023-10-01",
    EndDate: "2023-10-15",
    Priority: "low",
    CreatedBy: 1,
    AssignedTo: 2,
    Subtasks: [
      { SubtaskID: 5, Title: "Subtask 5", IsCompleted: false },
      { SubtaskID: 6, Title: "Subtask 6", IsCompleted: true },
    ],
  },
  {
    TaskID: 4,
    Title: "Task 4",
    Assignee: "Tarin",
    Description: "Description for Task 4",
    Status: "done",
    Tags: "meeting,urgent",
    StartDate: "2023-10-01",
    EndDate: "2023-10-15",
    Priority: "high",
    CreatedBy: 1,
    AssignedTo: 2,
    Subtasks: [
      { SubtaskID: 7, Title: "Subtask 7", IsCompleted: false },
      { SubtaskID: 8, Title: "Subtask 8", IsCompleted: true },
    ],
  },
];
